name             'bach_wrapper'
maintainer       'Bloomberg LP'
maintainer_email 'compute@bloomberg.net'
license          'All rights reserved'
description      'Top-level chef-bach wrapper'
long_description 'Top-level chef-bach wrapper'
version          '1.0.0-SNAPSHOT'

depends 'bach_common', '= 1.0.0-SNAPSHOT'
depends 'bach_spark', '= 1.0.0-SNAPSHOT'
depends 'bcpc', '= 1.0.0-SNAPSHOT'
depends 'bcpc-hadoop', '= 1.0.0-SNAPSHOT'
depends 'bcpc_jmxtrans', '= 1.0.0-SNAPSHOT'
depends 'hannibal', '= 1.0.0-SNAPSHOT'
depends 'kafka-bcpc', '= 1.0.0-SNAPSHOT'
