# -*- mode: ruby -*-
source "https://supermarket.chef.io"

metadata

# chef-vault from git, pending release to supermarket
cookbook 'chef-vault',
  git: 'https://github.com/chef-cookbooks/chef-vault',
  revision: 'cd45d3485b84392b46fd93e3aaeb65bf9b7ebff1'

# cobblerd forked, pending destruction of earth by moon.
cookbook 'cobblerd', 
  git: 'https://github.com/http-418/cobbler-cookbook'

# pdns forked, pending acceptance of a PR.
cookbook 'pdns',
  git: 'https://github.com/http-418/pdns'
