# -*- mode: ruby -*-
source "https://supermarket.chef.io"

metadata

# chef-vault forked, pending acceptance of a PR.
cookbook 'chef-vault',
  git: 'https://github.com/http-418/chef-vault'

# cobblerd 0.3.0 isn't on the supermarket.
cookbook 'cobblerd', 
  git: 'https://github.com/bloomberg/cobbler-cookbook',
  revision: '868334b4b4d3c760e9669a0adba0279e89d523bc'

# pdns forked, pending acceptance of a PR.
cookbook 'pdns',
  path: '/home/ajones/src.dev/pdns'
