source 'https://rubygems.org' do

  gem 'chef-rewind'
  gem 'chef-vault'
  gem 'mysql2'
  gem 'ruby-augeas'
  gem 'sequel'
  gem 'simple-graphite'
  gem 'zabbixapi'
  gem 'rspec', :require => false, :group => :test
  gem 'simplecov', :require => false, :group => :test
  gem 'simplecov-json', :require => false, :group => :test
  gem 'simplecov-rcov', :require => false, :group => :test
end
