source 'https://rubygems.org' do

  gem 'chef-rewind'
  gem 'chef-vault'
  gem 'ruby-augeas', :group => :cookbooks
  gem 'sequel'
  gem 'simple-graphite'
  gem 'mysql2', :group => :cookbooks
  gem 'zabbixapi', '>=2.4', :group => :cookbooks
  gem 'rspec', :require => false, :group => :test
  gem 'simplecov', :require => false, :group => :test
  gem 'simplecov-json', :require => false, :group => :test
  gem 'simplecov-rcov', :require => false, :group => :test
  gem 'faraday'
end
