default[:bach][:hive][:metastore][:port] = 9083
default[:bach][:hive][:hiveserver2][:port] = 10000
default[:bcpc][:hive][:heap][:size]=1024
default[:bcpc][:hive][:gc_opts] = " -verbose:gc -XX:+PrintHeapAtGC -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCDateStamps -Xloggc:/var/log/hive/gc/gc.log-$$-$(hostname)-$(date +'%Y%m%d%H%M').log -XX:+PrintTenuringDistribution -XX:+PrintGCApplicationStoppedTime -XX:+PrintGCApplicationConcurrentTime -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC"
default[:bcpc][:hadoop][:hive][:hiveserver2][:authentication][:method] = "KERBEROS"
default[:bcpc][:hadoop][:hive][:hiveserver2][:authentication][:ldap_url] = ""
default[:bcpc][:hadoop][:hive][:hiveserver2][:authentication][:ldap_domain] = ""
default[:bcpc][:hadoop][:hive][:hive_log_dir] = "/var/log/hive"
default[:bcpc][:hadoop][:hive][:hive_pid_dir] = "/var/run/hive"
default[:bcpc][:hadoop][:hive][:hive_ident_string] = "hive"
default[:bcpc][:hadoop][:hive][:metastore][:client][:socket][:timeout] = 3600
default[:bcpc][:hadoop][:hive][:javax][:jdo][:option][:ConnectionUserName] = "hive"
default[:bcpc][:hadoop][:hive][:datanucleus][:autoCreateSchema] = false
default[:bcpc][:hadoop][:hive][:datanucleus][:fixedDatastore] = true
default[:bcpc][:hadoop][:hive][:support][:concurrency] = true
default[:bcpc][:hadoop][:hive][:metastore][:execute][:setugi] = true
default[:bcpc][:hadoop][:hive][:warehouse][:subdir][:inherit][:perms] = true
default[:bcpc][:hadoop][:hive][:stats][:autogather] = true
default[:bcpc][:hadoop][:hive][:server2][:logging][:operation][:enabled] = true
default[:bcpc][:hadoop][:hive][:server2][:logging][:operation][:verbose] = true
