name 'smoke-tests'
maintainer       'Bloomberg Finance L.P.'
maintainer_email 'hadoop@bloomberg.net'
license          'Apache License 2.0'
description 'Installs/Configures smoke-tests'
long_description 'Installs/Configures smoke-tests'
version '3.5.0'
