#!/usr/bin/env python

import random
import boto
import boto.s3.connection
import unittest
import uuid
import time
 
from boto.s3.key import Key
 
class TestRadosGateway(object):
    def __init__(self, host, port, key, secret, is_secure):
        self.conn = boto.connect_s3(
            aws_access_key_id=key,
            aws_secret_access_key=secret,
            host=host,
            debug=0,  # adjust to your liking
            is_secure=is_secure, # False for HTTP, omit for HTTPS
            port=port,  # Port 80 for HTTP, omit for HTTPS
            calling_format=boto.s3.connection.OrdinaryCallingFormat())

        self.bucket_name = str(uuid.uuid1())

    def test(self):

        bucket = self.conn.create_bucket(self.bucket_name)
        if not bucket:
            return False, "Unable to create s3 bucket"
 
        if self.bucket_name not in [ b.name for b in self.conn.get_all_buckets()] :
            return False, "Unable to find bucket list" + str(self.conn.get_all_buckets())

        k = Key(bucket)
        k.key = 'key'
        k.set_contents_from_string('value')
 
        contents = k.get_contents_as_string()

        if contents != 'value':
            return False, "Return bucket contents no equal to input"
 
        if "key" not in [key.key for key in bucket.list()]:
            return False, "Key not returned in list bucket contents"  + ",".join(bucket.list())
          
        
        bucket.delete_key("key")
        self.conn.delete_bucket(self.bucket_name)
        
        time.sleep(1) # eventually consistent !
        if bucket in [ b for b in self.conn.get_all_buckets()] :
            return False, "deleted bucket still listed"

        return True, ""
 
if __name__ == '__main__':
    import yaml
    import sys
    config = yaml.load(open(sys.argv[1], "r"))
    rc = {}
    try:
        result, msg = TestRadosGateway(config["storage_vip"],
                                       config["storage_port"],
                                       config["access_key"],
                                       config["secret_key"],
                                       config["use_ssl"]).test();
        rc["msg"] = msg

        if result:
            rc["result"]= "OKAY"
        else:
            rc["result"] = "FAIL"
            
    except Exception as e:
        rc["result"] = "ERROR"
        rc["msg"] = str(e)

    print yaml.dump(rc)
 
