# -*- mode: yaml-mode -*-
---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: 12.3

provisioner:
  name: chef_zero
  http_proxy: <%= ENV['http_proxy'] %>
  https_proxy: <%= ENV['https_proxy'] %>
  client_rb:
    no_proxy: localhost
    http_proxy: <%= ENV['http_proxy'] %>
    https_proxy: <%= ENV['https_proxy'] %>

platforms:
  - name: ubuntu-12.04

suites:
  - name: bach_repository
    run_list:
      - recipe[apt]
      - recipe[bach_repository]
    attributes:
