# -*- mode: enh-ruby -*-
ruby RUBY_VERSION
if File.exist?('/opt/chefdk/Gemfile')
  # overload the path so we do not re-cache these gems
    opscode_gem_data = IO.read("/opt/chefdk/Gemfile")
    # strip off a Gem from a Git repo as it seems to confuse things
    opscode_gem_data.gsub!(/^gem.*opscode-pushy-client.*\n/,'')
    instance_eval(opscode_gem_data, "/opt/chefdk/Gemfile")
elsif File.exist?('/opt/chef/Gemfile')
  # overload the path so we do not re-cache these gems
    opscode_gem_data = IO.read("/opt/chef/Gemfile")
    instance_eval(opscode_gem_data, "/opt/chef/Gemfile")
else
  source 'https://rubygems.org' do

  gem 'berkshelf'
  gem 'kitchen-vagrant'
  gem 'serverspec'
  gem 'test-kitchen'
  gem 'builder'
  end
end
gem 'fpm'
