# -*- mode: enh-ruby -*-
source 'https://rubygems.org' do

  gem 'berkshelf'
  gem 'kitchen-vagrant'
  gem 'serverspec'
  gem 'test-kitchen'
  gem 'builder'
end
gem 'fpm', :git => 'https://github.com/cbaenziger/fpm' # workaround fpm #1197
