name             'bach_common'
maintainer       'Bloomberg LP'
maintainer_email 'hadoop@bloomberg.net'
license          'All rights reserved'
description      'bach_common contains common recipes for the BACH cookbooks'
long_description 'bach_common contains common recipes for the BACH cookbooks'
version          '3.0.0'

supports 'ubuntu', '12.04'
supports 'ubuntu', '14.04'
