---
driver:
  name: vagrant
  customize:
    memory: 2500

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list:
       - 'recipe[bach_ambari::default]'
    attributes: {
      java: {
        oracle: {
          accept_oracle_download_terms: true,
          jce: {
            enabled: true
          }
        },
        jdk_version: 8,
        install_flavor: oracle,
        accept_license_agreement: true,
        set_default: true
      }
    }
    driver:
      box: bento/ubuntu-14.04
      network:
      - [ "private_network" , { ip : "192.168.33.7" } ]
#      - [ "forwarded_port" , { guest : 8080, host : 8080 } ]
suites:
  - name: default
    attributes:
