# -*- mode: ruby -*-
source 'https://supermarket.chef.io'

metadata

group :integration do
  instance_eval(File.read('../../Berksfile.common'))

  cookbook 'bcpc_hadoop_test', path: 'test/cookbooks/bcpc_hadoop_test'
  cookbook 'bcpc', path: File.expand_path('../bcpc')
  cookbook 'bach_repository', path: File.expand_path('../bach_repository')
end
