# -*- mode: ruby -*-
source 'https://supermarket.chef.io'

metadata

group :integration do
  instance_eval(File.read('../../Berksfile.common'))
  cookbook 'bach_repository', path: '../bach_repository'
  cookbook 'bcpc_hadoop_test', path: 'test/cookbooks/bcpc_hadoop_test'
  cookbook 'bcpc', path: '../bcpc'
  cookbook 'smoke-tests', path: '../smoke-tests'
end
