source 'https://supermarket.chef.io'

cookbook 'bcpc-hadoop', path: '../bcpc-hadoop'
cookbook 'bach_ambari', path: '../bach_ambari'
cookbook 'bcpc', path: '../bcpc'
cookbook 'bach_krb5', path: '../bach_krb5'
cookbook 'smoke-tests', path: '../smoke-tests'
#cookbook 'locking_resource', path: '../locking_resource'
cookbook 'bach_opentsdb', path: '../bach_opentsdb'
group :integration do
  instance_eval(File.read('../../Berksfile.common'))

  cookbook 'bcpc', path: File.expand_path('../bcpc')
  cookbook 'bach_repository', path: File.expand_path('../bach_repository')
end

metadata
